site_name: iure-rtd-tutorial
site_description: Breve tutorial sobre aplicação crud

nav:
  - Home: index.md

theme:
  name: mkdocs
  palette:
    primary: "blue"
    accent: "teal"

markdown_extensions:
  - admonition
  - codehilite

plugins:
  - search
  - mkdocs-minify-plugin
